# Generated by Django 4.0.4 on 2022-12-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='can_request_timestamp',
        ),
    ]
