# Generated by Django 4.0.4 on 2022-12-05 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_can_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_request_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
