# Generated by Django 4.0.4 on 2022-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teammember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
