# Generated by Django 4.0.4 on 2022-12-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_unverifiedteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.speaker')),
            ],
        ),
    ]
