# Generated by Django 4.0.4 on 2022-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_teammember_email_alter_teammember_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
