# Generated by Django 4.0.4 on 2022-12-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('photo', models.FileField(upload_to='speakers/')),
            ],
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(),
        ),
    ]
