# Generated by Django 4.0.4 on 2022-12-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_speaker_alter_faqs_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQS',
            new_name='Faq',
        ),
    ]
