# Generated by Django 4.0.4 on 2022-12-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_faqs_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_request',
            field=models.BooleanField(default=True),
        ),
    ]
